### ISSUE TITLE
Adding custom share view?

### ISSUE THREAD

**Issue by BernardoOlisan** [OutdatedGuy/receive_sharing_intent_plus#11]
Hi!

This package is great because the other ones are not maintained. However, I was wondering if there is a way to add a custom share view. For example, instead of redirecting to the app itself when sharing intent, just open a modal with the app's design and add a footnote or caption, then send that caption or footnote with the shared image or URL and receive it in Flutter.

Where can I see how to do this?

**Comment by OutdatedGuy** [comment]
Hi, currently there is no such option for that and to implement it someone with knowledge of Java/Kotlin and Objc/Swift would be required.

I have just copied the un-maintained project and updated it to work on latest flutter so I don't fulfil the pre-requisites.

If you can implement the feature, feel free to do it. PRs are always welcomed.
