### ISSUE TITLE
 i am trying to share .ics file but it is not working?

### ISSUE THREAD

**Issue by Snofkin** [OutdatedGuy/receive_sharing_intent_plus#12]
I want to share the .ics file from Explorer. But when I try to do so, it is not responding as expected.It just didnt open the app

**Comment by OutdatedGuy** [comment]
Provide more information like:

1. Output of `flutter doctor -v`
2. Platform (android, ios, web, etc...)
3. Plugin Version
4. Sample code
5. Also, what is Explorer?
