### ISSUE TITLE
not sharing for background app in iOS

### ISSUE THREAD

**Issue by lagif** [OutdatedGuy/receive_sharing_intent_plus#13]
While it seems to work OK on iOS and pass files through the UserDefaults, when the app is already opened in the background, nothing happens, the listening channel seem to close immediately after the error: 

[User Defaults] Couldn't read values in CFPrefsPlistSource<0x283d34d80> (Domain: ****, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
********: [tcp] tcp_output [C16.1.2.1:3] flags=[R.] seq=497160602, ack=2743814988, win=3980 state=CLOSED rcv_nxt=2743814988, snd_una=497160602

**Comment by OutdatedGuy** [comment]
Hi, I'm not actively maintaining this package currently. Can you try with the [receive_sharing_intent](https://pub.dev/packages/receive_sharing_intent) plugin instead?

**Comment by lristic1310** [comment]
Hi @OutdatedGuy is the receive_sharing_intent plugin actively maintained?

**Comment by OutdatedGuy** [comment]
IDK, but it's the original plugin hence the author know what the native codes mean and is more updated than this plugin

**Comment by angcyo** [comment]
https://github.com/OutdatedGuy/receive_sharing_intent_plus/issues/15
