### ISSUE TITLE
in ios when you take a screenshot and try sharing it will not open the app

### ISSUE THREAD

**Issue by GhassenOmri645** [OutdatedGuy/receive_sharing_intent_plus#14]
i am facing a problem using this package it works perfectly in android and ios but only when sharing from screenshot if you can fix it or show me how it works i will be glad and thank you

**Comment by OutdatedGuy** [comment]
Hi, I'm not actively maintaining this package currently. Can you try with the [receive_sharing_intent](https://pub.dev/packages/receive_sharing_intent) plugin instead?

**Comment by GhassenOmri645** [comment]
okay thank you
