### ISSUE TITLE
Intent origin

### ISSUE THREAD

**Issue by MachariaK** [OutdatedGuy/receive_sharing_intent_plus#5]
When utilizing Flutter's receive_sharing_intent_plus, how can I determine the origin of the shared intent? I aim to identify the specific app.

**Comment by OutdatedGuy** [comment]
Yo @MachariaK, I didn't understand what your question/concern is.

Can you elaborate more and provide some examples.

**Comment by MachariaK** [comment]
I am currently using the 'receive_sharing_intent_plus' package in my Flutter project to receive data shared from other apps. However, I also need to identify the app that originally shared this intent with mine. Is there a feature within the package that provides details about the originating app that shared the intent? Can you provide any guidance or examples on how this can be achieved?

**Comment by OutdatedGuy** [comment]
@MachariaK, there is currently no way to get which app shared the data to our app using the plugin as I think Android and iOS doesn't share that info.

But if you find a way to do it PRs are always welcomed.
