### ISSUE TITLE
Installing rejected on iPhone simmulator

### ISSUE THREAD

**Issue by AshishDT** [OutdatedGuy/receive_sharing_intent_plus#7]
Unable to install /Users/deep/Desktop/MB/masalaboxflutter/build/ios/iphonesimulator/Runner.app on E2E455E8-905A-41BC-93F2-DEDF121EDC2D. This is sometimes caused by a malformed plist file:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=IXErrorDomain, code=2):
Simulator device returned an error for the requested operation.
Failed to create promise.
Underlying error (domain=IXErrorDomain, code=2):
	Failed to set app extension placeholders for com.yourgroup.app
	Failed to create promise.
  Command: /usr/bin/arch -arm64e xcrun simctl install E2E455E8-905A-41BC-93F2-DEDF121EDC2D /Users/deep/Desktop/MB/masalaboxflutter/build/ios/iphonesimulator/Runner.app
Error launching application on iPhone 14.

**Comment by OutdatedGuy** [comment]
> Failed to set app extension placeholders for com.yourgroup.app

Looks like you haven't followed the setup properly. Can you confirm that you have properly followed the [iOS Setup](https://pub.dev/packages/receive_sharing_intent_plus#setup-ios).

**Comment by AshishDT** [comment]
Closed
