### ISSUE TITLE
Direct share options

### ISSUE THREAD

**Issue by tejas-k8** [OutdatedGuy/receive_sharing_intent_plus#8]
Hello,
I am using this package and it's great to achieve share into the app feature.

As per latest iOS versions it will have the direct sharing options into the share bottom sheet of the system.

So, How can I do the same for my application by using this package?

**Comment by OutdatedGuy** [comment]
> As per latest iOS versions it will have the direct sharing options into the share bottom sheet of the system.

@tejas-du, can you link what this is and it's documentation so I can check it.

Also any images, videos and feature notes by Apple are appreciated.

**Comment by sdfgssdf** [comment]
Is there a way to share text directly like in the picture.In this case users do not need to switch apps

![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-05 at 01 12 46](https://github.com/OutdatedGuy/receive_sharing_intent_plus/assets/20835278/6ef948d8-69e1-44ec-bdfc-411d42e1166c)

**Comment by OutdatedGuy** [comment]
Hi, I don't have an iOS device to know of this feature. But i'll research on this when I get some free time.

Till then it would be better and appreciated if you provide these to me:
> can you link what this is and it's documentation so I can check it.
> 
> Also any images, videos and feature notes by Apple are appreciated.
